name: Terraform linting workflow
description: Runs Terraform linting actions
outputs:
  linting:
    description: Terraform linting output
    value: ${{ steps.linting.outcome }}
runs:
  using: 'composite'
  steps:
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Setup Linter
      uses: terraform-linters/setup-tflint@v3
    - name: Linter Version
      shell: bash
      run: tflint --version
    - name: Linter Initialize
      shell: bash
      run: tflint --init
    - name: Linting Code
      id: linting
      shell: bash
      run: tflint -f compact